!obj:pylearn2.train.Train {
    dataset: &train !obj:ds.PatientStatusDataset {
        which_set: "train",
        one_hot: 1,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 20,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [98, 98],
            num_channels: 2
        },
        layers: [
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h0',
                     output_channels: 64,
                     irange: .05,
                     kernel_shape: [3, 3],
                     border_mode: 'full',
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     tied_b: True,
                     W_lr_scale: .5,
                     max_kernel_norm: 2.9365,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h1',
                     output_channels: 64,
                     irange: .05,
                     kernel_shape: [3, 3],
                     border_mode: 'full',
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     tied_b: True,
                     W_lr_scale: .5,
                     max_kernel_norm: 2.9365,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h2',
                     output_channels: 96,
                     irange: .05,
                     kernel_shape: [3, 3],
                     border_mode: 'full',
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     tied_b: True,
                     W_lr_scale: .5,
                     max_kernel_norm: 2.9365,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h3',
                     output_channels: 96,
                     irange: .05,
                     kernel_shape: [3, 3],
                     border_mode: 'full',
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     tied_b: True,
                     W_lr_scale: .5,
                     max_kernel_norm: 2.9365,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                     layer_name: 'h4',
                     output_channels: 96,
                     irange: .05,
                     kernel_shape: [3, 3],
                     border_mode: 'full',
                     pool_shape: [2, 2],
                     pool_stride: [2, 2],
                     tied_b: True,
                     W_lr_scale: .5,
                     max_kernel_norm: 2.9365,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h5',
                     dim: 512,
                     sparse_init: 15,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h6',
                     dim: 128,
                     sparse_init: 15,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h7',
                     dim: 64,
                     sparse_init: 15,
                     left_slope: .01,
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     max_col_norm: 2.9365,
                     layer_name: 'y',
                     n_classes: 5,
                     istdev: .05
                 }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        batch_size: 20,
        learning_rate: .002,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5
        },
        monitoring_dataset:
            {
                'train' : *train,
                'test'  : !obj:ds.PatientStatusDataset {
                              which_set: 'test',
                              one_hot: 1,
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts { costs: [
            !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X'
            }, !obj:pylearn2.costs.mlp.WeightDecay {
                coeffs: [ .00005, .00005, .00005, .00005, .00005, .00005, .00005, .00005, .00005 ]
            }
            ]
        },
        termination_criterion: !obj:pylearn2.termination_criteria.Or {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "test_y_misclass",
                    prop_decrease: 0.0,
                    N: 40
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 50
                },
            ]
        },
    },
    extensions:
        [ !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'test_y_misclass',
             save_path: "cnn_best_new.pkl"
        }, !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 10,
            final_momentum: .99
        }
    ],
    save_path: 'cnn_new.pkl',
    save_freq: 1,
}


